# Generated by Django 4.2.1 on 2024-05-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_created_with_tasks',
            field=models.BooleanField(default=True),
        ),
    ]
