# Generated by Django 5.0.2 on 2024-02-28 13:48

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=clients.models.get_user_image_path),
        ),
    ]
