# Generated by Django 4.2.1 on 2024-05-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
